services:
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9091:9091"
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio@1234
    volumes:
      - "/Users/allen/Documents/Docker/minio/data:/data"
    command: server /data --console-address ":9091"
    restart: always
  kafka:
    image: apache/kafka:latest
    ports:
      - "9092:9092"
    volumes:
      - "/Users/allen/Documents/Docker/kafka/config:/mnt/shared/config"
      - "/Users/allen/Documents/Docker/kafka/data:/var/lib/kafka/data"
      - "/Users/allen/Documents/Docker/kafka/secret:/etc/kafka/secrets"
    environment:
      - LANG=C.UTF-8
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_NODE_ID=1
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9093
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://host.docker.internal:9092
  nacos:
    image: nacos/nacos-server:latest
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    environment:
      - MODE=standalone
    volumes:
      - "/Users/allen/Documents/Docker/nacos/conf:/home/nacos/conf"
      - "/Users/allen/Documents/Docker/nacos/data:/home/nacos/data"
      - "/Users/allen/Documents/Docker/nacos/logs:/home/nacos/logs"
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - "/Users/allen/Documents/Docker/mysql/data:/var/lib/mysql"
