services:
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9091:9091"
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio@1234
    volumes:
      - "/Users/allen/Documents/Docker/minio/data:/data"
    command: server /data --console-address ":9091"
    restart: always
  kafka:
    image: bitnami/kafka:3.6.2
    ports:
      - "9092:9092"
      - "9094:9094"
    volumes:
      - "/Users/allen/Documents/Docker/kafka:/bitnami/kafka"
    environment:
      - TZ=Asia/Shanghai
      - LANG=C.UTF-8
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@localhost:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://host.docker.internal:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
#    restart: always
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
  nacos:
    image: nacos/nacos-server:latest
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    environment:
      - MODE=standalone
    volumes:
      - "/Users/allen/Documents/Docker/nacos/conf:/home/nacos/conf"
      - "/Users/allen/Documents/Docker/nacos/data:/home/nacos/data"
      - "/Users/allen/Documents/Docker/nacos/logs:/home/nacos/logs"
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - "/Users/allen/Documents/Docker/mysql/data:/var/lib/mysql"
