server:
  port: 9090

spring:
  datasource:
    meta:
      url: jdbc:mysql://localhost:3306/leek_meta?serverTimezone=GMT&seUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&autoReconnect=true&allowPublicKeyRetrieval=true
      username: leek_dev
      password: leek_dev
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        minimum-idle: 5
        maximum-pool-size: 20
        idle-timeout: 30000
        pool-name: AdminDataSourceHikariCP
        max-lifetime: 60000
        connection-timeout: 30000
    admin:
      url: jdbc:mysql://localhost:3306/leek_admin?serverTimezone=GMT&seUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&autoReconnect=true&allowPublicKeyRetrieval=true
      username: leek_dev
      password: leek_dev
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        minimum-idle: 5
        maximum-pool-size: 20
        idle-timeout: 30000
        pool-name: AdminDataSourceHikariCP
        max-lifetime: 60000
        connection-timeout: 30000
    backtest:
      url: jdbc:mysql://localhost:3306/leek_backtest?serverTimezone=GMT&seUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&autoReconnect=true&allowPublicKeyRetrieval=true
      username: leek_dev
      password: leek_dev
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        minimum-idle: 5
        maximum-pool-size: 20
        idle-timeout: 30000
        pool-name: BackTestDataSourceHikariCP
        max-lifetime: 60000
        connection-timeout: 30000
    future:
      url: jdbc:mysql://localhost:3306/leek_future?serverTimezone=GMT&seUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&autoReconnect=true&allowPublicKeyRetrieval=true
      username: leek_dev
      password: leek_dev
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        minimum-idle: 5
        maximum-pool-size: 20
        idle-timeout: 30000
        pool-name: FutureDataSourceHikariCP
        max-lifetime: 60000
        connection-timeout: 30000
    stock:
      url: jdbc:mysql://localhost:3306/leek_stock?serverTimezone=GMT&seUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&autoReconnect=true&allowPublicKeyRetrieval=true
      username: leek_dev
      password: leek_dev
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        minimum-idle: 5
        maximum-pool-size: 20
        idle-timeout: 30000
        pool-name: FutureDataSourceHikariCP
        max-lifetime: 60000
        connection-timeout: 30000
  jpa:
    admin:
      show-sql: true
      properties:
        hibernate:
          hbm2ddl:
            auto: update
          dialect: org.hibernate.dialect.MySQL8Dialect
    backtest:
      show-sql: true
      properties:
        hibernate:
          hbm2ddl:
            auto: update
          dialect: org.hibernate.dialect.MySQL8Dialect
    future:
      show-sql: true
      properties:
        hibernate:
          hbm2ddl:
            auto: update
          dialect: org.hibernate.dialect.MySQL8Dialect