server:
  port: 9091

spring:
  datasource:
    meta:
      enabled: true
      url: jdbc:mysql://localhost:3306/leek_meta?serverTimezone=GMT&seUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&autoReconnect=true&allowPublicKeyRetrieval=true
      username: leek_dev
      password: leek_dev
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        minimum-idle: 5
        maximum-pool-size: 20
        idle-timeout: 30000
        pool-name: MeteDataSourceHikariCP
        max-lifetime: 60000
        connection-timeout: 30000
    jpa:
      meta:
        show-sql: true
        properties:
          hibernate:
            hbm2ddl:
              auto: update
            dialect: org.hibernate.dialect.MySQL8Dialect